on:
  push:
    branches:
      - "main"
  repository_dispatch:
    types: [my-event]
  # schedule:
  #   - cron: "0,5,10,15,20,25,30,35,40,45,50,55 * * * *"

jobs:
  fetch-json-data:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v2
      - run: |
          git fetch --no-tags --prune --depth=1 origin +refs/heads/*:refs/remotes/origin/*
    
      - name: push
        run: |
          bash ./script.sh
      - name: Repository Dispatch
        uses: actions/github-script@v2
        with:
          github-token: ${{secrets.JUN_TOKEN}}
          script: |
            const fs = require('fs');
            await github.repos.createDispatchEvent({
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    event_type: "my-event",
                    client_payload: { greeting: "I'm Meeseek. Loot at me!" }
                  });